version: '3'
services:
  db:
    image: postgis/postgis:16-3.4-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - umap_db:/opt/igisit/postgresql/data

  integration:
    build: .
    image: integration:latest
    ports:
      - "8080:8080"

  umap:
    image: umap/umap:1.8.2
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgis://postgres@db/postgres
      - SITE_URL=https://localhost:8001/
      - STATIC_ROOT=/srv/umap/static
      - MEDIA_ROOT=/srv/umap/uploads
    volumes:
      - umap_userdata:/srv/umap/uploads
      - ./umap.conf:/etc/umap/umap.conf
    restart: always
    depends_on:
      - db

volumes:
  umap_userdata:
  umap_db:
