version: '3.9'

services:

  db:
    image: postgis/postgis:16-3.4-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - umap_db:/opt/igisit/postgresql/data

  integration:
    image: ostis-metro-middleware:latest
    expose:
      - 80
    ports:
      - "8002:8002"

  umap:
    image: umap/umap:1.8.2
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgis://postgres@db/postgres
      - SITE_URL=https://localhost:8001/
      - STATIC_ROOT=/srv/umap/static
      - MEDIA_ROOT=/srv/umap/uploads
    volumes:
      - umap_userdata:/srv/umap/uploads
      - ./umap.conf:/etc/umap/umap.conf
    restart: always
    depends_on:
      - db

  web:
    image: ostis/sc-web:0.8.0-Fusion
    restart: unless-stopped
    ports:
      - "8000:8000"
    command:
      - "--server-host=machine"
    depends_on:
      machine:
        condition: service_healthy

  machine:
    image: ostis/sc-machine:0.8.0-Fusion
    restart: unless-stopped
    volumes:
      - ./ostis-web-platform/:/kb
      - kb-binary:/kb.bin
    ports:
      - "8090:8090"
    healthcheck:
      test: "python3 /sc-machine/scripts/healthcheck.py"
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 120s
    environment:
      # Use the commented env variable if you need to rebuild KB every startup.
      #- "REBUILD_KB=1"
      - "KB_PATH=/kb/repo.path"
      - "BINARY_PATH=/sc-machine/bin"
      - "CONFIG_PATH=/kb/ostis-web-platform.ini"
    command:
      - "serve"

volumes:
  kb-binary: {}
  umap_userdata:
  umap_db:

networks:
  default:
    name: ostis-metro-network
